export const projects = [
  {
    title: 'Paroki Santo Petrus',
    description: "Alamat : Jl. Merdeka 14, Bandung 40117",
    image: '/images/petrus.jpg',
    tags: ['Hari Minggu: 06.00, 09.00, 12.00, 17.00','Hari Sabtu: 06.00, 17.00', 'Misa harian: 06.00, 17.00'],
    source: 'https://goo.gl/maps/PQf1QRfcJ4zeX3ik6',
    visit: 'https://katedralbandung.org/',
    id: 0,
  },
  {
    title: 'Paroki Santa Odilia',
    description:"Alamat: Jl. Cikutra 7, Bandung 40124",
    image: '/images/odelia.jpeg',
    tags: ['Hari Minggu: 06.00, 09.00, 12.00, 17.00', 'Hari Sabtu: 06.00, 17.00', 'Misa Harian: 06.00, 17.00'],
    source: 'https://goo.gl/maps/66HT1BfrTJKvyjhu8',
    visit: 'https://odiliacicadas.com/',
    id: 1,
  },
  {
    title: 'Paroki Santa Melania',
    description: "Alamat: Jl. Melania 1-3 (blk.RRI), Bandung 40122",
      image: '/images/melania.jpeg',
      tags: ['Hari Minggu: 09.00', 'Hari Sabtu: 06.00, 17.00', 'Misa harian: 06.00'],
    source: 'https://goo.gl/maps/NFqfr7h8rxp46arm8',
    visit: 'https://keuskupanbandung.org/section-item/64',
    id: 2,
  },
  {
    title: 'Paroki Salib Suci',
    description: "Alamat: Jl. Kamuning 25, Bandung 40113",
    image: '/images/salib_suci.jpeg',
    tags: ['Hari Minggu: 05.45, 07.00, 08.30, 17.00', 'Hari Sabtu: 05.45, 17.00', 'Misa harian: 05.45'],
    source: 'https://goo.gl/maps/RuiMKf6Vb7mY3LSv5',
    visit: 'https://www.keuskupanbandung.org/section-item/65',
    id: 3,
  },
  {
    title: 'Paroki Santa Maria Fatima',
    description: "Alamat: Jl. Karmel 112, Lembang 40391",
    image: '/images/maria_fatima.jpg',
    tags: ['Hari Minggu: 08.00', 'Hari Sabtu: 17.45', 'Misa harian: 06.30'],
    source: 'https://goo.gl/maps/95oiw7M6FzqDyySY8',
    visit: 'https://www.instagram.com/paroki.lembang/?hl=en',
    id: 4,
  },
  {
    title: 'Paroki Santo Laurentius',
    description: "Alamat: Jl. Sukajadi 223, Bandung 40153",
    image: '/images/laurentius.jpg',
    tags: ['Hari Minggu: 07.00, 09.30, 17.00', 'Hari Sabtu: 06.00, 17.00', 'Misa harian: 06.00'],
    source: 'https://goo.gl/maps/GWmxhcCFxpRQpoLe8',
    visit: 'https://parokilaurentiusbdg.org/',
    id: 5,
  },
  {
    title: 'Paroki Santo Ignatius',
    description: "Alamat: Jl. Baros 8, Cimahi 40521",
    image: '/images/ignatius.jpg',
    tags: ['Hari Minggu: 05.30, 07.30, 09.30, 17.00', 'Hari Sabtu: 17.00', 'Misa harian: 06.00'],
    source: 'https://goo.gl/maps/1ydQjqaQ4zNxHCUN6',
    visit: 'https://www.instagram.com/stignatius_cimahi/?hl=en',
    id: 6,
  },
  {
    title: 'Paroki Bunda Tujuh Kedukaan',
    description: "Alamat: Jl. Pandu 4, Bandung 40173",
    image: '/images/pandu.jpg',
    tags: ['Hari Minggu: 06.00, 08.00, 10.00, 17.30', 'Hari Sabtu: 06.00, 17.30', 'Misa harian: 06.00'],
    source: 'https://goo.gl/maps/ziPFVyPpWVdddbkMA',
    visit: 'https://pandu.katolik.or.id/',
    id: 7,
  },
  {
    title: 'Paroki Santo Theodorus',
    description: "Alamat: Jl. Unpar II No. 10, Bandung, 40164",
    image: '/images/theodorus.jpg',
    tags: ['Hari Minggu: 07.00, 09.30, 17.00', 'Hari Sabtu: 06.00', 'Misa harian: 06.00'],
    source: 'https://goo.gl/maps/mNoBGS5ozHmiMnkk9',
    visit: 'http://theodorus.org/',
    id: 8,
  },
  {
    title: 'Paroki Santo Fransiskus Xaverius',
    description: "Alamat: Jl. Bojongsoang No. 17 Dayeuhkolot, Kab. Bandung 40257",
    image: '/images/fransiskus.jpg',
    tags: ['Hari Minggu: 07.00, 10.00', 'Hari Sabtu: 06.00', 'Misa harian: 06.00'],
    source: 'https://goo.gl/maps/pV8xUuxVL78KFXwSA',
    visit: 'http://gerejadyhkolot.com/',
    id: 9,
  },
  {
    title: 'Paroki Santo Gabriel',
    description: "Alamat: Jl. Sumber Makmur No. 4 Kompleks Sumber Sari Indah, Bandung 40222",
    image: '/images/gabriel.jpg',
    tags: ['Hari Minggu: 07.00, 09.00', 'Hari Sabtu: 06.00, 18.00', 'Misa harian: 06.00'],
    source: 'https://goo.gl/maps/pH6kTTwfeeY2PiLZ9',
    visit: 'https://keuskupanbandung.org/section-item/72',
    id: 10,
  },
  {
    title: 'Paroki Santo Martinus',
    description: "Alamat: Jl. Hercules IV / Dakkota No. 2, Lanud Sulaeman, Kab. Bandung",
    image: '/images/martinus.jpg',
    tags: ['Hari Minggu: 06.00, 08.00 10.00 18.00', 'Hari Sabtu: 06.00, 18.00', 'Misa harian: 06.00'],
    source: 'https://goo.gl/maps/kbfbx1HAwZywYpQe9',
    visit: 'https://parokimartinusbdg.org/',
    id: 11,
  },
  {
    title: 'Paroki Santo Michael',
    description: "Alamat: Jl. Waringin 51, Bandung 40182",
    image: '/images/michael.jpg',
    tags: ['Hari Minggu: 07.00, 09.30', 'Hari Sabtu: 06.00, 17.30', 'Misa harian: 06.00'],
    source: 'https://goo.gl/maps/T3n47fyNUJnm9X3v7',
    visit: 'https://www.gerejastmichael.com/',
    id: 12,
  },
  {
    title: 'Paroki Santo Paulus',
    description: "Alamat: Jl. Mohammad Toha 19-21, Bandung 40252",
    image: '/images/paulus.jpg',
    tags: ['Hari Minggu: 06.00, 08.00, 10.00, 17.00', 'Hari Sabtu: 05.45, 17.00', 'Misa harian: 05.45'],
    source: 'https://goo.gl/maps/vZtLfkFpuUBi5Cc98',
    visit: 'https://www.instagram.com/komsos.stpaulus/?hl=en',
    id: 13,
  },
  {
    title: 'Paroki Hati Tak Bernoda Santa Perawan Maria',
    description: "Alamat: Jl. Suryalaya 3, Buah Batu, Bandung 40265",
    image: '/images/maria.jpg',
    tags: ['Hari Minggu: 06.00, 08.00, 10.15, 17.00', 'Hari Sabtu: 05.45, 17.00', 'Misa harian: 05.45'],
    source: 'https://goo.gl/maps/ayqcnJbHLLEpRKGWA',
    visit: 'https://www.parokihtbspm.org/',
    id: 14,
  },
  {
    title: 'Gereja Mahasiswa Bandung',
    description: "Alamat: Jl. Sultan Agung No.2, Citarum, Kec. Bandung Wetan, Kota Bandung, Jawa Barat 40115",
    image: '/images/gema.jpg',
    tags: ['Hari Minggu: 08.00'],
    source: 'https://goo.gl/maps/kwWcoWJ47ex9Q9Um8',
    visit: 'http://www.gerejamahasiswabandung.id/gema/',
    id: 14,
  },
];
